### ISSUE TITLE
Inconsistent button conventions

### ISSUE THREAD

**Issue by joehakimrahme** [Elie-Soued/todolist-frontend#7]
![image](https://user-images.githubusercontent.com/300964/196006215-f7d2129a-88a9-4500-a65d-226bfa359cc4.png)

The actions to edit, delete, accept an edit, cancel an edit, all have beautiful icon/drawing buttons. However the button to add a new Todo is written in latin letters `Add`.

This is ugly and inconsistent.

**Comment by joehakimrahme** [comment]
PS: I'm not sure a button for `Add` is necessary at all. Users know to press `Enter`. It might be a different story for mobile though.

**Comment by Elie-Soued** [comment]
Issue resolved with this commit 63c31fe
