### ISSUE TITLE
Inconsistent font - "Not Registered Yet ?"

### ISSUE THREAD

**Issue by joehakimrahme** [Elie-Soued/todolist-frontend#8]
![image](https://user-images.githubusercontent.com/300964/196006293-de0160c0-52f9-49ca-b322-aa16c1c4db66.png)

The phrase "Not Registered Yet ?" is written in a font different from the rest of the app. You should unify the fonts. Also I think the font of "Not Registered Yet ?" is prettier than the default font on the rest of the app.

PS: [In English, it is always an error to have  a space before the exclamation mark](https://english.stackexchange.com/questions/4645/is-it-ever-correct-to-have-a-space-before-a-question-or-exclamation-mark). (It's not the case for French).

**Comment by Elie-Soued** [comment]
Issue solved with commit b5227fa and 5ee2b11
